### PR TITLE
(Week 1 Day 3): Add Array and Functions homework

### PR DESCRIPTION
**Pull request by robinsonlam**
**How difficult did you find this (out of 10)?**
1
**Was there anything that you struggled with?** 
Not particularly, it helped when I was explaining how to do things to others when I was trying to solve the problems, it also helped me to get a better understanding of the things I explained to others.
**Is there anything that you'd like some further information on?**
Writing cleaner code, I think it's more to do with my problem solving/logic, I may be writing more code than I need to.. I probably need to go over my code again and try to clean it up.
**Roughly, how long did it take?**
2-3 hours. 

I think I'm missing quite a bit of extra stuff too such as dealing with uppercase/lowercase letters etc. but I've completed the homework as required of the spec

### CODE REVIEW

**Comment by robinsonlam** [comment]
Objects Homework D4

**How difficult did you find this (out of 10)?**
2

**Was there anything that you struggled with?** 
I was wondering if it was actually asking me to do some more complex/tedious things or not but was reminded of the heron formula and found out formulas to find out if a triangle is obtuse. 
Also wondered if my objects and functions were laid out correctly.

**Is there anything that you'd like some further information on?**
Nope

**Roughly, how long did it take?**
2-3 hours.

**Comment by ga-wolf** [comment]
Really great work.  Nice, clean code. It's cool to see all your code Robinson - great stuff!

**Comment by ga-wolf** [comment]
If I were you, I would be having a look at things like ternary operators and try and catch blocks. I feel like you would appreciate the stuff that they offer

**Comment by robinsonlam** [comment]
Interesting... I'll definitely take a look at try and catch blocks, I've used ternary operators in a previous exercise, they're awesome

**Pull request merged**
