### PR TITLE
Week 05 Day 01 

### PR DESCRIPTION
**Pull request by robinsonlam**
I'm finding I'm learning quite smoothly but I may not be putting enough thought into some of it.

I ran into a problem where I couldn't use the query params properly so instead I set the route to "games/rps/result" instead of "games/rps/:throw" and made it do calculations in there, I'd like to talk more about this.
# Other than that I'm understanding everything so far

Homework Day 02

Added some routes, will finish in the morning, got home quite late after Node Workshop

### CODE REVIEW

**Comment by ga-wolf** [comment]
Looks good mate, grab me if you want to have a chat about the result vs :throw thing.  How'd the Node thing go?

**Comment by robinsonlam** [comment]
Node went alright, a bit underwhelming, started off really slow, wasn't
until the last 10 minutes when it picked up and we made our web server

On Wed, Sep 2, 2015 at 12:49 PM, ga-wolf notifications@github.com wrote:

> Looks good mate, grab me if you want to have a chat about the result vs
> :throw thing. How'd the Node thing go?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ga-wolf/WDI10-Homework/pull/88#issuecomment-136918301
> .

## 

*Robinson Lam *| UI/UX Designer and Front End Developer

_www.robinsonlam.com http://www.robinsonlam.com_

**Comment by ga-wolf** [comment]
Oh, that’s a shame. We will cover a bit of Node at the end of the course anyway!

-- 

Jack Jeffress | Web Development Immersive Instructor
+61 415 124 849 | jack.jeffress@generalassemb.ly
Level M, 56 - 58 York Street, Sydney, NSW, 2000, Aus.

On 2 September 2015 at 2:26:22 pm, Robinson Lam (notifications@github.com) wrote:

Node went alright, a bit underwhelming, started off really slow, wasn't
until the last 10 minutes when it picked up and we made our web server

On Wed, Sep 2, 2015 at 12:49 PM, ga-wolf notifications@github.com wrote:

> Looks good mate, grab me if you want to have a chat about the result vs
> :throw thing. How'd the Node thing go?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ga-wolf/WDI10-Homework/pull/88#issuecomment-136918301
> .

## 

*Robinson Lam *| UI/UX Designer and Front End Developer

_www.robinsonlam.com http://www.robinsonlam.com_

**Comment by robinsonlam** [comment]
sounds good... I"m gunna message you on Slack about my idea for my project

On Wed, Sep 2, 2015 at 2:29 PM, ga-wolf notifications@github.com wrote:

> Oh, that’s a shame. We will cover a bit of Node at the end of the course
> anyway!
> 
> ## 
> 
> Jack Jeffress | Web Development Immersive Instructor
> +61 415 124 849 | jack.jeffress@generalassemb.ly
> Level M, 56 - 58 York Street, Sydney, NSW, 2000, Aus.
> 
> On 2 September 2015 at 2:26:22 pm, Robinson Lam (notifications@github.com)
> wrote:
> 
> Node went alright, a bit underwhelming, started off really slow, wasn't
> until the last 10 minutes when it picked up and we made our web server
> 
> On Wed, Sep 2, 2015 at 12:49 PM, ga-wolf notifications@github.com wrote:
> 
> > Looks good mate, grab me if you want to have a chat about the result vs
> > :throw thing. How'd the Node thing go?
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/ga-wolf/WDI10-Homework/pull/88#issuecomment-136918301>
> > .
> 
> ## 
> 
> *Robinson Lam *| UI/UX Designer and Front End Developer
> 
> _www.robinsonlam.com http://www.robinsonlam.com_
> 
> —
> Reply to this email directly or view it on GitHub.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ga-wolf/WDI10-Homework/pull/88#issuecomment-136934754
> .

## 

*Robinson Lam *| UI/UX Designer and Front End Developer

_www.robinsonlam.com http://www.robinsonlam.com_

**Pull request merged**
