### PR TITLE
 added unfinished homework week 1 day 2

### PR DESCRIPTION
**Pull request by Melk2015Sydney**
How difficult did you find this (out of 10)? 0 being no problems at all, 10 being impossible
I found the concept of functions to be interesting, however I struggled being a beginner. 
Was there anything that you struggled with?
I struggled with some of the terms. var, function etc what comes first
Is there anything that you'd like some further information on?
Maybe just some step by step examples, sometimes it is good to see the end in mind- the big picture and deconstruct it to make some meaning, then reconstruct with another example question very familiar to the initial question. 

Roughly, how long did it take?
for the few examples... it took me 40 minutes. A long time.

### CODE REVIEW

**Comment by ga-wolf** [comment]
You have done a great job with all of this stuff. All of these come with practice, and trust me - you will get lots and lots of that! Hopefully today helped getting you used to all of this stuff. How are you feeling now with it all?   Make sure you let me know if you want to have a chat about anything!

**Comment by Melk2015Sydney** [comment]
Being Indigenous I am very much a Communal Learner, I love to learn in small groups and learn off each other, not just visually but in a round about way. I see the JS can be a non-Linear activity because you can get to a solution two or three different ways, I know I will have the ah-ha moment soon, just have to empty my cup more to learn new things, maybe Im just a little seasoned compared to others. The metalanguage in JS, CSS and various software will take some time getting used to... no doubt I will ask alot of silly dumb questions,,, and go 'doh' afterwards,,, my way of processing stuff. I will definitely chat to you to ask many questions trust me, I will need the support. Thank you Jack.

**Comment by Melk2015Sydney** [comment]
Thank you for affirmation and confidence. Appreciation.

**Comment by Melk2015Sydney** [comment]
Just want to touch base to say thanks to you guys. You guys are amazingly clever and talented, I just wish I was cut out for that stuff. I transferred to the UX course in September. Anyhow, I appreciate the expertise you guys have. 
Thank you

**Pull request merged**
